project:
  type: website
  output-dir: docs

website:
  title: "Mukherjee Lab"
  page-navigation: true
  navbar:
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: People
        href: people.qmd
      - text: Alumnae
        href: alumnae.qmd
      - text: Software
        href: software.qmd
      - text: Research
        href: research.qmd
      - text: Education and Outreach
        href: education-outreach
      - text: Public Health DSDE at Yale
        href: https://www.google.com/
        target: _blank

language: 
  search-text-placeholder: Search  # Placeholder text for Search

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



